---
title: "MIA Data Preparation and Analysis"
author: "Ray Erickson"
date: today
format:
  html:
    theme: spacelab
    backgroundcolor: "#DCDCE3"
    monobackgroundcolor: "#DEDEDE"
    fontcolor: "black"
    toc: true
    toc-depth: 3
    toc-expand: true
    toc-location: left
    code-fold: false
    code-overflow: wrap
    embed-resources: true
    tabsets: true
    grid:
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
editor_options:
  markdown:
    wrap: none
jupyter: python3
---
```{python}
#| include: false
#Importing the needed libraries
import pandas as pd
import matplotlib.pyplot as plt
import us
import geopandas
import re
from offline_folium import offline
import folium
#assign file path
file = "AZ-ALWY.xlsx"
usmapfile = "us-states.json"
worldmapfile = "countries.geojson"
usmap = geopandas.read_file(usmapfile)
worldmap = geopandas.read_file(worldmapfile)
```

# Setup, Aggregation, and Base Visualization


>For this project you will need the `pandas`, `matplotlib.pyplot`, `us`, `geopandas`, and `re` libraries

Due to the size of some of the maps, they are included as links to html files hosted in this github folder. As of yet, they are not automatically up to date, but I should be fairly on top of making sure they are the latest versions I have made.

:::{.panel-tabset}

## Data Importation & Cleaning
:::{.panel-tabset}

### Importing Original Files
```{python}
byalph = pd.read_excel(file, "A-Z", index_col=None, na_values=["NA"]) 
```
This call reads the excel file, specifically the sheet named "A-Z" into a dataframe without a predefined index and includes no special variables to be assigned as missing values.

<ul>Sheet *A-Z* is the compiled list of the MIA individuals downloaded alphabetically</ul>
```{python}
#| echo: false
byalph.info()
```


```{python}
bystate = pd.read_excel(file, "AL-WY", index_col=None, na_values=["NA"]) 
```
This call reads the excel file, specifically the sheet named "AL-WY" into a dataframe without a predefined index and includes no special variables to be assigned as missing values.

<ul>Sheet AL-WY is the compiled list of the MIA individuals downloaded by state.</ul>
```{python}
#| echo: false
bystate.info()
```

### Merging Files into a single DB


```{python}
merged = byalph.merge(bystate, how='outer', on=["Last_Name","First_Name","Conflict"])
```
This code merges the state and alphabetical dataframes based on the `First_Name`, `Last_Name`, and `Confict`, as these are the only columns that exist on both sheets, as well as being the standardized ones, and generally have no nulls. Since they are not in and of themselves unique, the combination of all three is needed to appropriately merge the dataframes.

```{python}
#| echo: false
merged.info()
```

### Cleaning

The dataframe has some quantity of duplicates, likely due to some amount of syntactical differences, ex. name has a middle initial on one and not the other, etc...
```{python}
cleaned = merged.drop_duplicates(subset=["Last_Name", "Service_Number"])
```
drop duplicates based upon service number, with last name as a index in order to not drop all null service numbers as duplicates
```{python}
#| echo: false
cleaned.info()
```


```{python}
cleaned = cleaned.drop(cleaned[(cleaned.Home_of_Record == "NON-US")].index)
```
Drop all records that have the `home of record` listed as Non-US, narrowing the dataframe to only those from the US
```{python}
#| echo: false
cleaned.info()
```


```{python}
cleaned = cleaned.dropna(subset = ["State","Conflict"])
```
Drop all records that have null values in the `State` field as they will not be useful for analysis
```{python}
#| echo: false
cleaned.info()
```

Additionally, while the Army Air Force and the Air Force are technically different entities, because the Army Air Force is the Air Force precursor, for analysis purposes, I have combined the two together.

### Anonomizing Data


```{python}
todrop = ["Last_Name", "First_Name", "Service_Number", "Unit", "Home_of_Record", "Rank"]
anon = cleaned.drop(columns=todrop)
```
Drop the names and service numbers in order to anonomize data, as well as Unit, since the unit data is not currently standardized and to do so would take massive amounts of time, and Home of Record since it is duplicated by state to a degree and state is a more accurate identifier, and Rank since its not standardized, nor currently in use in this analysis

```{python}
anon["Date_of_Loss"]=pd.to_datetime(anon["Date_of_Loss"])
anon["Year_of_Loss"]=anon["Date_of_Loss"].dt.year
anon["Date_of_Loss"]=anon["Date_of_Loss"].dt.date
anon["State_Name"] = anon["State"].map(lambda x: us.states.lookup(x).name)
```

I am also making sure the `Date of Loss` column is in DateTime format and then making it only have the date not a unneeded time value, and adding a `Year of Loss` column for added analysis options. As well as adding a `State Name` column for ease of understanding.
```{python}
#| echo: false
#| 
anon.info()
```

I then export the anonomized data to an excel sheet to simplify further actions.

```{python}
#| eval: false
anon.to_excel("mia_anon.xlsx")
```

:::

## Data Aggregation

First I am going to aggregate the data based upon the different main variables in order to make analysis easier at a later time. Additionally I am adding some additional reference values for sorting purposes

``` {python}
#|echo: False
conflictcount = anon.groupby("Conflict").agg(Count=("State","count"))
conflictcount["Start_Year"]=[1947,1950,1991,1986,2003,1955,1939]
conflictcount["End_Year"]=[1991,1953,1991,1986,2011,1975,1945]

print("Missing count by conflict")
print(conflictcount)
```

```{python}
#| echo: false
servicecount = anon.groupby("Service").agg(Count=("State","count"))
print("Missing count by Service") 
print(servicecount)
```

```{python}
#| echo: false

statecount = anon.groupby("State").agg(Count=("Conflict","count"))
statecount["State_Name"] = statecount.index.map(lambda x: us.states.lookup(x).name)

print("Highest 10 State Missing Counts")
print(statecount.sort_values("Count", ascending=False)[:10])
```

```{python}
#| echo: false

yearcount = anon.groupby("Year_of_Loss").agg(Count=("State","count"))
print("Highest 10 Missing Counts by Year")
print(yearcount.sort_values("Count", ascending=False)[:10])
```

```{python}
#| echo: false

datecount = anon.groupby("Date_of_Loss").agg(Count=("State","count"))
print("Highest 10 Missing Counts by Date ")
print(datecount.sort_values("Count", ascending=False)[:10])
```

```{python}
#| echo: false

locationcount = anon.groupby("Location").agg(Count=("State","count"))
locationcount.index = locationcount.index.str.title()
print("Highest 10 State Missing Counts")
print(locationcount.sort_values("Count", ascending=False)[:10])
```

To do further analysis I am also including the reserves within the main branch to simplify things a little


## Base Visualization

:::{.panel-tabset}

### Missing per Conflict

```{python}
#|echo: false

cnfplt = conflictcount.sort_values("Start_Year",  ascending=False).plot(
    title="Missing per Conflict",
    kind="barh",
    y="Count",
    legend=False,
    color="grey"
    )
for p in cnfplt.patches:
    value = p.get_width()
    cnfplt.annotate(
        str(value),
        (value, p.get_y() + p.get_height() / 2),
        ha="left", va="center", xytext=(5, 0), textcoords="offset points")
cnfplt.set_xlim( conflictcount["Count"].max() * 1.15, 0)
cnfplt.invert_xaxis()
plt.show()
```

### Missing per Service

```{python}
#| echo: false

def pielegpct(data, title):
    pcts = (data/data.sum()*100).round(2)
    leglab = [f"{label} ({pct}%)" for label, pct in zip(data.index, pcts)]
    plt.pie(data,labels=data.index, labeldistance=None)
    plt.legend(leglab, bbox_to_anchor=(1,1.1), loc="upper left")
    plt.title(title)
    plt.tight_layout()
        
pielegpct(servicecount["Count"], "Distribution of Missing by Services")
plt.show()
```

### Missing by Home State

```{python}
#| echo: false
usmaps = usmap.merge(
    statecount.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )
fig, ax = plt.subplots(figsize=(35, 7))
usmaps.plot(column="Count", ax=ax, legend=True, cmap='YlOrRd', edgecolor='k')
ax.set_title('Missing by State')
ax.set_axis_off()
plt.show()

stplt = statecount.sort_values("Count",  ascending=True).plot(
    title="Complete Missing per State",
    kind="barh",
    y="Count",
    legend=False,
    color="gray",
    figsize=(5,15)
    )
for p in stplt.patches:
    value = p.get_width()
    stplt.annotate(
        str(value),
        (value, p.get_y() + p.get_height() / 2),
        ha="left", va="center", xytext=(5, 0), textcoords="offset points")
stplt.set_xlim( statecount["Count"].max() * 1.15, 0)
stplt.invert_xaxis()


```

### Date of Loss

```{python}
#| echo: false
yearcount.plot(kind="line", y="Count", title="Missing by Year of Loss", legend=False)
plt.show()
```


```{python}
#| echo: false
datecount.plot(kind="line", y="Count", title="Missing by Date of Loss", legend=False)
plt.show()
```

### Missing by Location of Loss

```{python}
#| echo: false
locmatching = {
  'Baker Island': 'United States Minor Outlying Islands', 
  'Wake Island':'United States Minor Outlying Islands', 
  'Martinique': "France", #not technically, but I think on this map it is included 
  'Korea': "South Korea", 
  'Tokelau': "New Zealand", 
  'Johnston Atoll': 'United States Minor Outlying Islands', 
  'Serbia': 'Republic of Serbia', 
  'Czech Republic': 'Czechia', 
  'Federated States Of Micronesia':'Federated States of Micronesia',
  'Saint Helena, Ascension, And Tristan Da Cunha':'Saint Helena',  
  'Trinidad And Tobago':'Trinidad and Tobago', 
  'Bosnia And Herzegovina':'Bosnia and Herzegovina', 
  'United States':'United States of America', 
  'Curacao':'Curaçao', 
  'Wallis And Futuna':'Wallis and Futuna', 
  'French Guiana': "France",# this is not geographically part of France, but I am fairly certain that it is included geographically 
  'Hong Kong':'Hong Kong S.A.R.', 
  'Palmyra Atoll':'United States Minor Outlying Islands', 
  'U.S. Virgin Islands': 'United States Virgin Islands', 
  'Midway Islands': 'United States Minor Outlying Islands', 
  'Burma':'Myanmar', 
  'Christmas Island': "Australia"
  }
maplocnt=locationcount
maplocnt = maplocnt.rename(index=locmatching)
maplocnt = maplocnt.groupby(level=0).sum()


worldmaps = worldmap.merge(
    maplocnt.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )
fig, ax = plt.subplots(figsize=(35, 5.65))
worldmaps.plot(column='Count', ax=ax, legend=True, cmap='YlOrRd', edgecolor='k')
ax.set_title('Missing by Location')
ax.set_axis_off()
plt.show()

locplt = locationcount.sort_values("Count",  ascending=True).plot(
    title="Complete Missing per Location",
    kind="barh",
    y="Count",
    legend=False,
    color="gray",
    figsize=(5,35)
    )
for p in locplt.patches:
    value = p.get_width()
    locplt.annotate(
        str(value),
        (value, p.get_y() + p.get_height() / 2),
        ha="left", va="center", xytext=(5, 0), textcoords="offset points")
locplt.set_xlim( locationcount["Count"].max() * 1.15, 0)
locplt.invert_xaxis()

```

### Conflict Breakdown per Service

```{python}
#|echo: False
analysis=anon
analysis["Service"]=analysis["Service"].str.replace("UNITED STATES ", "")
analysis["Service"]=analysis["Service"].str.replace(" RESERVE", "")
```

```{python}
#|echo: False

bysvc = analysis.groupby("Service")
srv_cnf = pd.crosstab(analysis["Conflict"], analysis["Service"],normalize="index").round(4)*100

print(srv_cnf)
```

The following pie charts show the breakdown of service missing per conflict
```{python}
#| echo: False
for name, group in bysvc:
    fig, ax = plt.subplots(figsize=(5,5))
    catcount=group["Conflict"].value_counts(normalize=True)*100
    catcount=catcount.round(2)
    leglab=[f"{cat} ({count}%)" for cat, count in catcount.items()]
    wedges, autotexts = ax.pie(catcount, startangle=90)
    ax.legend(wedges, leglab, loc="upper left", bbox_to_anchor=(1, 0, 0.5, 1))
    plt.title(f"{name}")
    plt.show()
```


:::

## Conflict Analysis

I am combining the conflicts beside World War II, the Korean War, and the Vietnam War into "Other Conflicts" maps in order to more clearly show the data since they make up such a small percentage of the missing.

#### World War II: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/ww2stmap.html)

#### World War II: Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/ww2locmap.html)

#### Korean War: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/kwarstmap.html)

#### Korean War: Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/kwarlocmap.html)

#### Vietnam War: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/vwarstmap.html)

#### Vietnam War: Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/vwarlocmap.html)

#### Other Conflicts: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/owarstmap.html)

#### Other Conflicts: Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/owarlocmap.html)

## Service Analysis

I am also combining the other services beside the Army, Air Force, Navy, and Marine Corps because they as well make up a small percentage of the missing.

#### US Air Force: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/afstmap.html)

#### US Air Force: Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/aflocmap.html)

#### US Army: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/armystmap.html)

#### US Army: Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/armylocmap.html)

#### US Navy: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/navystmap.html)

#### US Navy Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/navylocmap.html)

#### US Marine Corps: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/mcstmap.html)

#### US Marine Corps: Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/mclocmap.html)

#### Other Services: Missing by Home State

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/osvcstmap.html)

#### Other Services: Missing by Location of Loss

[Interactive map](http://htmlpreview.github.io/?https://github.com/reric4/MIA_Data_Analysis/blob/main/Maps/osvclocmap.html)

## Conclusions

World War II is overwhelmingly the originating conflict for the majority of MIA soldiers, as well as the highest percentage of loss for all of the services

Overall the US Navy has the most MIA soldiers. 

California overall has the most MIA soldiers, although New York has more MIA from World War II than California does

California has the most MIA Navy and Marines, while New York has the most MIA Army, Air Force, and other services

The Solomon Islands have the highest concentration of MIA missing, including the highest concentration of Marine Corps and Navy missing, as well as the highest concentration of World War II missing.

North Korea has the highest concentration of both Korean War missing, and Army missing.

Papua New Guinea has the highest concentration of Air Force missing.

The highest concentration of missing from other conflicts is in Russia, while the highest concentration of missing from other services is Greenland.

:::

```{python}
#|echo: false


ww2 = analysis[analysis["Conflict"]=="WORLD WAR II"]
kwar = analysis[analysis["Conflict"]=="KOREAN WAR"]
vwar = analysis[analysis["Conflict"]=="VIETNAM WAR"]
owar = analysis[analysis["Conflict"]!="WORLD WAR II"]
owar = owar[owar["Conflict"]!="KOREAN WAR"]
owar = owar[owar["Conflict"]!="VIETNAM WAR"]

usaf = analysis[analysis["Service"]=="AIR FORCE"]
usarmy = analysis[analysis["Service"]=="ARMY"]
usnavy = analysis[analysis["Service"]=="NAVY"]
usmc = analysis[analysis["Service"]=="MARINE CORPS"]
osvc = analysis[analysis["Service"]!="AIR FORCE"]
osvc = osvc[osvc["Service"]!="ARMY"]
osvc = osvc[osvc["Service"]!="NAVY"]
osvc = osvc[osvc["Service"]!="MARINE CORPS"]
osvc = osvc.dropna(subset=["Service"])
```
```{python}
#| include: false
ww2st=ww2.groupby("State").agg(Count=("State_Name","count"))
ww2st["State_Name"] = ww2st.index.map(lambda x: us.states.lookup(x).name)
ww2stmap = usmap.merge(ww2st.reset_index(), left_on="name", right_on="State_Name", how="left")
ww2stmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
ww2stmap.rename(columns={"Count":"Missing"}, inplace=True)
ww2stmap = ww2stmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
ww2stmap.save("Maps/ww2stmap.html")

#---

kwarst=kwar.groupby("State").agg(Count=("State_Name","count"))
kwarst["State_Name"] = kwarst.index.map(lambda x: us.states.lookup(x).name)
kwarstmap = usmap.merge(kwarst.reset_index(), left_on="name", right_on="State_Name", how="left")
kwarstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
kwarstmap.rename(columns={"Count":"Missing"},inplace=True)
kwarstmap=kwarstmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
kwarstmap.save("Maps/kwarstmap.html")

#---

vwarst=vwar.groupby("State").agg(Count=("State_Name","count"))
vwarst["State_Name"] = vwarst.index.map(lambda x: us.states.lookup(x).name)
vwarstmap = usmap.merge(vwarst.reset_index(), left_on="name", right_on="State_Name", how="left")
vwarstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
vwarstmap.rename(columns={"Count":"Missing"},inplace=True)
vwarstmap=vwarstmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
vwarstmap.save("Maps/vwarstmap.html")

#---

owarst=owar.groupby("State").agg(Count=("State_Name","count"))
owarst["State_Name"] = owarst.index.map(lambda x: us.states.lookup(x).name)
owarstmap = usmap.merge(owarst.reset_index(), left_on="name", right_on="State_Name", how="left")
owarstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
owarstmap.rename(columns={"Count":"Missing"},inplace=True)
owarstmap=owarstmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
owarstmap.save("Maps/owarstmap.html")

#---

afst=usaf.groupby("State").agg(Count=("State_Name","count"))
afst["State_Name"] = afst.index.map(lambda x: us.states.lookup(x).name)
afstmap = usmap.merge(afst.reset_index(), left_on="name", right_on="State_Name", how="left")
afstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
afstmap.rename(columns={"Count":"Missing"},inplace=True)
afstmap=afstmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
afstmap.save("Maps/afstmap.html")

#---

armyst=usarmy.groupby("State").agg(Count=("State_Name","count"))
armyst["State_Name"] = armyst.index.map(lambda x: us.states.lookup(x).name)
armystmap = usmap.merge(armyst.reset_index(), left_on="name", right_on="State_Name", how="left")
armystmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
armystmap.rename(columns={"Count":"Missing"},inplace=True)
armystmap=armystmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
armystmap.save("Maps/armystmap.html")

#---

navyst=usnavy.groupby("State").agg(Count=("State_Name","count"))
navyst["State_Name"] = navyst.index.map(lambda x: us.states.lookup(x).name)
navystmap = usmap.merge(navyst.reset_index(), left_on="name", right_on="State_Name", how="left")
navystmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
navystmap.rename(columns={"Count":"Missing"},inplace=True)
navystmap=navystmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
navystmap.save("Maps/navystmap.html")

#---

mcst=usmc.groupby("State").agg(Count=("State_Name","count"))
mcst["State_Name"] = mcst.index.map(lambda x: us.states.lookup(x).name)
mcstmap = usmap.merge(mcst.reset_index(), left_on="name", right_on="State_Name", how="left")
mcstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
mcstmap.rename(columns={"Count":"Missing"},inplace=True)
mcstmap=mcstmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
mcstmap.save("Maps/mcstmap.html")

#---

osvcst=osvc.groupby("State").agg(Count=("State_Name","count"))
osvcst["State_Name"] = osvcst.index.map(lambda x: us.states.lookup(x).name)
osvcstmap = usmap.merge(osvcst.reset_index(), left_on="name", right_on="State_Name", how="left")
osvcstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
osvcstmap.rename(columns={"Count":"Missing"},inplace=True)
osvcstmap=osvcstmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
osvcstmap.save("Maps/osvcstmap.html")

#---

ww2loc=ww2.groupby("Location").agg(Count=("State_Name","count"))
ww2locmap =worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
ww2locmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
ww2locmap.rename(columns={"Count":"Missing"}, inplace=True)
ww2locmap=ww2locmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
ww2locmap.save("Maps/ww2locmap.html")

#---

kwarloc=kwar.groupby("Location").agg(Count=("State_Name","count"))
kwarlocmap = worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
kwarlocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
kwarlocmap.rename(columns={"Count":"Missing"},inplace=True)
kwarlocmap=kwarlocmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
kwarlocmap.save("Maps/kwarlocmap.html")

#---

vwarloc=vwar.groupby("Location").agg(Count=("State_Name","count"))
vwarlocmap = worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
vwarlocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
vwarlocmap.rename(columns={"Count":"Missing"},inplace=True)
vwarlocmap=vwarlocmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
vwarlocmap.save("Maps/vwarlocmap.html")

#---

owarloc=owar.groupby("Location").agg(Count=("State_Name","count"))
owarlocmap = worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
owarlocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
owarlocmap.rename(columns={"Count":"Missing"},inplace=True)
owarlocmap=owarlocmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
owarlocmap.save("Maps/owarlocmap.html")

#---

afloc=usaf.groupby("Location").agg(Count=("State_Name","count"))
aflocmap = worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
aflocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
aflocmap.rename(columns={"Count":"Missing"},inplace=True)
aflocmap=aflocmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
aflocmap.save("Maps/aflocmap.html")

#---

armyloc=usarmy.groupby("Location").agg(Count=("State_Name","count"))
armylocmap = worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
armylocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
armylocmap.rename(columns={"Count":"Missing"},inplace=True)
armylocmap=armylocmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
armylocmap.save("Maps/armylocmap.html")

#---

navyloc=usnavy.groupby("Location").agg(Count=("State_Name","count"))
navylocmap = worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
navylocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
navylocmap.rename(columns={"Count":"Missing"},inplace=True)
navylocmap=navylocmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
navylocmap.save("Maps/navylocmap.html")

#---

mcloc=usmc.groupby("Location").agg(Count=("State_Name","count"))
mclocmap = worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
mclocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
mclocmap.rename(columns={"Count":"Missing"},inplace=True)
mclocmap=mclocmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
mclocmap.save("Maps/mclocmap.html")

#---

osvcloc=osvc.groupby("Location").agg(Count=("State_Name","count"))
osvclocmap = worldmap.merge(maplocnt.reset_index(), left_on="name", right_on="Location", how="left")
osvclocmap.drop(columns={"ISO3166-1-Alpha-2", "ISO3166-1-Alpha-3","Location"},inplace=True)
osvclocmap.rename(columns={"Count":"Missing"},inplace=True)
osvclocmap=osvclocmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
osvclocmap.save("Maps/osvclocmap.html")
```
