---
title: "MIA Data Setup & Base Visualization"
author: "Ray Erickson"
date: today
format:
  html:
    theme: spacelab
    backgroundcolor: "#DCDCE3"
    monobackgroundcolor: "#DEDEDE"
    fontcolor: "black"
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
    code-overflow: wrap
    embed-resources: true
    tabsets: true
    grid:
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
editor_options:
  markdown:
    wrap: none
jupyter: python3
---
```{python setup}
#| echo: False
#Importing the needed libraries
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import us
import geopandas
import re
#assign file path
file = "AZ-ALWY.xlsx"
usmapfile = "us-states.json"
worldmapfile = "countries.geojson"
usmap = geopandas.read_file(usmapfile)
worldmap = geopandas.read_file(worldmapfile)
```

# Setup, Aggregation, and Base Visualization


>For this project you will need the `pandas`, `matplotlib.pyplot`, `us`, `geopandas`, and `re` libraries

Also, due to the size of the data, this project is split into three files, so the `pickle` package is needed in order to export the variables from one doc to the other.

:::{.panel-tabset}

## Data Importation & Cleaning
:::{.panel-tabset}

### Importing Original Files
```{python}
byalph = pd.read_excel(file, "A-Z", index_col=None, na_values=["NA"]) 
```
This call reads the excel file, specifically the sheet named "A-Z" into a dataframe without a predefined index and includes no special variables to be assigned as missing values.

<ul>Sheet *A-Z* is the compiled list of the MIA individuals downloaded alphabetically</ul>
```{python}
#| echo: false
byalph.info()
```


```{python}
bystate = pd.read_excel(file, "AL-WY", index_col=None, na_values=["NA"]) 
```
This call reads the excel file, specifically the sheet named "AL-WY" into a dataframe without a predefined index and includes no special variables to be assigned as missing values.

<ul>Sheet AL-WY is the compiled list of the MIA individuals downloaded by state.</ul>
```{python}
#| echo: false
bystate.info()
```

### Merging Files into a single DB


```{python}
merged = byalph.merge(bystate, how='outer', on=["Last_Name","First_Name","Conflict"])
```
This code merges the state and alphabetical dataframes based on the `First_Name`, `Last_Name`, and `Confict`, as these are the only columns that exist on both sheets, as well as being the standardized ones, and generally have no nulls. Since they are not in and of themselves unique, the combination of all three is needed to appropriately merge the dataframes.

```{python}
#| echo: false
merged.info()
```

### Cleaning

The dataframe has some quantity of duplicates, likely due to some amount of syntactical differences, ex. name has a middle initial on one and not the other, etc...
```{python}
cleaned = merged.drop_duplicates(subset=["Last_Name", "Service_Number"])
```
drop duplicates based upon service number, with last name as a index in order to not drop all null service numbers as duplicates
```{python}
#| echo: false
cleaned.info()
```


```{python}
cleaned = cleaned.drop(cleaned[(cleaned.Home_of_Record == "NON-US")].index)
```
Drop all records that have the `home of record` listed as Non-US, narrowing the dataframe to only those from the US
```{python}
#| echo: false
cleaned.info()
```


```{python}
cleaned = cleaned.dropna(subset = "State")
```
Drop all records that have null values in the `State` field as they will not be useful for analysis
```{python}
#| echo: false
cleaned.info()
```

Additionally, while the Army Air Force and the Air Force are technically different entities, because the Army Air Force is the Air Force precursor, for analysis purposes, I have combined the two together.

### Anonomizing Data


```{python}
todrop = ["Last_Name", "First_Name", "Service_Number", "Unit", "Home_of_Record", "Rank"]
anon = cleaned.drop(columns=todrop)
```
Drop the names and service numbers in order to anonomize data, as well as Unit, since the unit data is not currently standardized and to do so would take massive amounts of time, and Home of Record since it is duplicated by state to a degree and state is a more accurate identifier, and Rank since its not standardized, nor currently in use in this analysis

```{python}
anon["Date_of_Loss"]=pd.to_datetime(anon["Date_of_Loss"])
anon["Year_of_Loss"]=anon["Date_of_Loss"].dt.year
anon["Date_of_Loss"]=anon["Date_of_Loss"].dt.date
anon["State_Name"] = anon["State"].map(lambda x: us.states.lookup(x).name)
```

I am also making sure the `Date of Loss` column is in DateTime format and then making it only have the date not a unneeded time value, and adding a `Year of Loss` column for added analysis options. As well as adding a `State Name` column for ease of understanding.
```{python}
#| echo: false
#| 
anon.info()
```

I then export the anonomized data to an excel sheet to simplify further actions.

```{python}
#| eval: false
anon.to_excel("mia_anon.xlsx")
```

:::

## Data Aggregation

First I am going to aggregate the data based upon the different main variables in order to make analysis easier at a later time. Additionally I am adding some additional reference values for sorting purposes

``` {python}
#|echo: False
conflictcount = anon.groupby("Conflict").agg(Count=("State","count"))
conflictcount["Start_Year"]=[1947,1950,1991,1986,2003,1955,1939]
conflictcount["End_Year"]=[1991,1953,1991,1986,2011,1975,1945]

print("Missing count by conflict")
print(conflictcount)
```

```{python}
#| echo: false
servicecount = anon.groupby("Service").agg(Count=("State","count"))
print("Missing count by Service") 
print(servicecount)
```

```{python}
#| echo: false

statecount = anon.groupby("State").agg(Count=("Conflict","count"))

statecount["State_Name"] = statecount.index.map(lambda x: us.states.lookup(x).name)

print("Highest 10 State Missing Counts")
print(statecount.sort_values("Count", ascending=False)[:10])
```

```{python}
#| echo: false

yearcount = anon.groupby("Year_of_Loss").agg(Count=("State","count"))
print("Highest 10 Missing Counts by Year")
print(yearcount.sort_values("Count", ascending=False)[:10])
```

```{python}
#| echo: false

datecount = anon.groupby("Date_of_Loss").agg(Count=("State","count"))
print("Highest 10 Missing Counts by Date ")
print(datecount.sort_values("Count", ascending=False)[:10])
```

```{python}
#| echo: false

locationcount = anon.groupby("Location").agg(Count=("State","count"))

locationcount.index = locationcount.index.str.title()
print("Highest 10 State Missing Counts")
print(locationcount.sort_values("Count", ascending=False)[:10])
```

To do further analysis I am also including the reserves within the main branch to simplify things a little


## Base Visualization

:::{.panel-tabset}

### Missing per Conflict

```{python}
#|echo: false

cnfplt = conflictcount.sort_values("Start_Year",  ascending=False).plot(
    title="Missing per Conflict",
    kind="barh",
    y="Count",
    legend=False,
    color="grey"
    )
for p in cnfplt.patches:
    value = p.get_width()
    cnfplt.annotate(
        str(value),
        (value, p.get_y() + p.get_height() / 2),
        ha="left", va="center", xytext=(5, 0), textcoords="offset points")
cnfplt.set_xlim( conflictcount["Count"].max() * 1.15, 0)
cnfplt.invert_xaxis()
plt.show()
```

### Missing per Service

```{python}
#| echo: false

def pielegpct(data, title):
    pcts = (data/data.sum()*100).round(2)
    leglab = [f"{label} ({pct}%)" for label, pct in zip(data.index, pcts)]
    
    plt.pie(data,labels=data.index, labeldistance=None)
    plt.legend(leglab, bbox_to_anchor=(1,1.1), loc="upper left")
    plt.title(title)
    plt.tight_layout()
        
pielegpct(servicecount["Count"], "Distribution of Missing by Services")
plt.show()
```

### Missing by Home State

```{python}
#| echo: false
usmaps = usmap.merge(
    statecount.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )
fig, ax = plt.subplots(figsize=(35, 7))
usmaps.plot(column="Count", ax=ax, legend=True, cmap='YlOrRd', edgecolor='k')
ax.set_title('Missing by State')
ax.set_axis_off()
plt.show()

stplt = statecount.sort_values("Count",  ascending=True).plot(
    title="Complete Missing per State",
    kind="barh",
    y="Count",
    legend=False,
    color="gray",
    figsize=(5,15)
    )
for p in stplt.patches:
    value = p.get_width()
    stplt.annotate(
        str(value),
        (value, p.get_y() + p.get_height() / 2),
        ha="left", va="center", xytext=(5, 0), textcoords="offset points")
stplt.set_xlim( statecount["Count"].max() * 1.15, 0)
stplt.invert_xaxis()


```

### Date of Loss

```{python}
#| echo: false
yearcount.plot(kind="line", y="Count", title="Missing by Year of Loss", legend=False)
plt.show()
```


```{python}
#| echo: false
datecount.plot(kind="line", y="Count", title="Missing by Date of Loss", legend=False)
plt.show()
```

### Missing by Location of Loss

```{python}
#| echo: false
locmatching = {
  'Baker Island': 'United States Minor Outlying Islands', 
  'Wake Island':'United States Minor Outlying Islands', 
  'Martinique': "France", #not technically, but I think on this map it is included 
  'Korea': "South Korea", 
  'Tokelau': "New Zealand", 
  'Johnston Atoll': 'United States Minor Outlying Islands', 
  'Serbia': 'Republic of Serbia', 
  'Czech Republic': 'Czechia', 
  'Federated States Of Micronesia':'Federated States of Micronesia',
  'Saint Helena, Ascension, And Tristan Da Cunha':'Saint Helena',  
  'Trinidad And Tobago':'Trinidad and Tobago', 
  'Bosnia And Herzegovina':'Bosnia and Herzegovina', 
  'United States':'United States of America', 
  'Curacao':'Curaçao', 
  'Wallis And Futuna':'Wallis and Futuna', 
  'French Guiana': "France",# this is not geographically part of France, but I am fairly certain that it is included geographically 
  'Hong Kong':'Hong Kong S.A.R.', 
  'Palmyra Atoll':'United States Minor Outlying Islands', 
  'U.S. Virgin Islands': 'United States Virgin Islands', 
  'Midway Islands': 'United States Minor Outlying Islands', 
  'Burma':'Myanmar', 
  'Christmas Island': "Australia"
  }
maplocationcount=locationcount
maplocationcount = maplocationcount.rename(index=locmatching)
maplocationcount = maplocationcount.groupby(level=0).sum()


worldmaps = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )
fig, ax = plt.subplots(figsize=(35, 5.65))
worldmaps.plot(column='Count', ax=ax, legend=True, cmap='YlOrRd', edgecolor='k')
ax.set_title('Missing by Location')
ax.set_axis_off()
plt.show()

locplt = locationcount.sort_values("Count",  ascending=True).plot(
    title="Complete Missing per Location",
    kind="barh",
    y="Count",
    legend=False,
    color="gray",
    figsize=(5,35)
    )
for p in locplt.patches:
    value = p.get_width()
    locplt.annotate(
        str(value),
        (value, p.get_y() + p.get_height() / 2),
        ha="left", va="center", xytext=(5, 0), textcoords="offset points")
locplt.set_xlim( locationcount["Count"].max() * 1.15, 0)
locplt.invert_xaxis()

```

### Conflict Breakdown per Service

```{python}
#|echo: False
analysis=anon
analysis["Service"]=analysis["Service"].str.replace("UNITED STATES ", "")
analysis["Service"]=analysis["Service"].str.replace(" RESERVE", "")
```

```{python}
#|echo: False

bysvc = analysis.groupby("Service")
srv_cnf = pd.crosstab(analysis["Conflict"], analysis["Service"],normalize="index").round(4)*100

print(srv_cnf)
```

The following pie charts show the breakdown of service missing per conflict
```{python}
#| echo: False
for name, group in bysvc:
    fig, ax = plt.subplots(figsize=(5,5))
    catcount=group["Conflict"].value_counts(normalize=True)*100
    catcount=catcount.round(2)
    leglab=[f"{cat} ({count}%)" for cat, count in catcount.items()]
    wedges, autotexts = ax.pie(catcount, startangle=90)
    ax.legend(wedges, leglab, loc="upper left", bbox_to_anchor=(1, 0, 0.5, 1))
    plt.title(f"{name}")
    plt.show()
```


:::
:::

---


```{python}
#|echo: false


ww2 = analysis[analysis["Conflict"]=="WORLD WAR II"]
kwar = analysis[analysis["Conflict"]=="KOREAN WAR"]
vwar = analysis[analysis["Conflict"]=="VIETNAM WAR"]
owar = analysis[analysis["Conflict"]!="WORLD WAR II"]
owar = owar[owar["Conflict"]!="KOREAN WAR"]
owar = owar[owar["Conflict"]!="VIETNAM WAR"]

usaf = analysis[analysis["Service"]=="AIR FORCE"]
usarmy = analysis[analysis["Service"]=="ARMY"]
usnavy = analysis[analysis["Service"]=="NAVY"]
usmc = analysis[analysis["Service"]=="MARINE CORPS"]
osvc = analysis[analysis["Service"]!="AIR FORCE"]
osvc = osvc[osvc["Service"]!="ARMY"]
osvc = osvc[osvc["Service"]!="NAVY"]
osvc = osvc[osvc["Service"]!="MARINE CORPS"]
osvc = osvc.dropna(subset=["Service"])
```
```{python}
#|echo: false
ww2st=ww2.groupby("State").agg(Count=("State_Name","count"))
ww2st["State_Name"] = ww2st.index.map(lambda x: us.states.lookup(x).name)
ww2_stmap = usmap.merge(
    ww2st.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )
ww2_stmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
ww2_stmap.rename(columns={"Count":"Missing"}, inplace=True)

ww2loc=ww2.groupby("Location").agg(Count=("State_Name","count"))
ww2_locmap =worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )
ww2_locmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
ww2_locmap.rename(columns={"Count":"Missing"}, inplace=True)
```
```{python}
#|echo: false
kwarst=kwar.groupby("State").agg(Count=("State_Name","count"))
kwarst["State_Name"] = kwarst.index.map(lambda x: us.states.lookup(x).name)
kwar_stmap = usmap.merge(
    kwarst.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )

kwar_stmap.drop(columns={"State_Name", "id", "density"},inplace=True)
kwar_stmap.rename(columns={"Count":"Missing"},inplace=True)

kwarloc=kwar.groupby("Location").agg(Count=("State_Name","count"))
kwar_locmap = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )

kwar_locmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
kwar_locmap.rename(columns={"Count":"Missing"},inplace=True)
```
```{python}
#|echo: false
vwarst=vwar.groupby("State").agg(Count=("State_Name","count"))
vwarst["State_Name"] = vwarst.index.map(lambda x: us.states.lookup(x).name)
vwar_stmap = usmap.merge(
    vwarst.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )

vwar_stmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
vwar_stmap.rename(columns={"Count":"Missing"},inplace=True)

vwarloc=vwar.groupby("Location").agg(Count=("State_Name","count"))
vwar_locmap = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )

vwar_locmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
vwar_locmap.rename(columns={"Count":"Missing"},inplace=True)
```
```{python}
#|echo: false
owarst=owar.groupby("State").agg(Count=("State_Name","count"))
owarst["State_Name"] = owarst.index.map(lambda x: us.states.lookup(x).name)
owar_stmap = usmap.merge(
    owarst.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )

owar_stmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
owar_stmap.rename(columns={"Count":"Missing"},inplace=True)

owarloc=owar.groupby("Location").agg(Count=("State_Name","count"))
owar_locmap = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )

owar_locmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
owar_locmap.rename(columns={"Count":"Missing"},inplace=True)
```
```{python}
#|echo: false

afst=usaf.groupby("State").agg(Count=("State_Name","count"))
afst["State_Name"] = afst.index.map(lambda x: us.states.lookup(x).name)

afstmap = usmap.merge(
    afst.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )

afstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
afstmap.rename(columns={"Count":"Missing"},inplace=True)

afloc=usaf.groupby("Location").agg(Count=("State_Name","count"))
aflocmap = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )

aflocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
aflocmap.rename(columns={"Count":"Missing"},inplace=True)
```
```{python}
#|echo: false
armyst=usarmy.groupby("State").agg(Count=("State_Name","count"))
armyst["State_Name"] = armyst.index.map(lambda x: us.states.lookup(x).name)

armystmap = usmap.merge(
    armyst.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )

armystmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
armystmap.rename(columns={"Count":"Missing"},inplace=True)

armyloc=usarmy.groupby("Location").agg(Count=("State_Name","count"))
armylocmap = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )

armylocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
armylocmap.rename(columns={"Count":"Missing"},inplace=True)
```
```{python}
#|echo: false
navyst=usnavy.groupby("State").agg(Count=("State_Name","count"))
navyst["State_Name"] = navyst.index.map(lambda x: us.states.lookup(x).name)

navystmap = usmap.merge(
    navyst.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )

navystmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
navystmap.rename(columns={"Count":"Missing"},inplace=True)

navyloc=usnavy.groupby("Location").agg(Count=("State_Name","count"))
navylocmap = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )

navylocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
navylocmap.rename(columns={"Count":"Missing"},inplace=True)
```
```{python}
#|echo: false
mcst=usmc.groupby("State").agg(Count=("State_Name","count"))
mcst["State_Name"] = mcst.index.map(lambda x: us.states.lookup(x).name)

mcstmap = usmap.merge(
    mcst.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )

mcstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
mcstmap.rename(columns={"Count":"Missing"},inplace=True)

mcloc=usmc.groupby("Location").agg(Count=("State_Name","count"))
mclocmap = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )

mclocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
mclocmap.rename(columns={"Count":"Missing"},inplace=True)
```
```{python}
#|echo: false
otherst=osvc.groupby("State").agg(Count=("State_Name","count"))
otherst["State_Name"] = otherst.index.map(lambda x: us.states.lookup(x).name)

otherstmap = usmap.merge(
    otherst.reset_index(),
    left_on="name",
    right_on="State_Name",
    how="left"
    )

otherstmap.drop(columns={"State_Name", "State", "id", "density"},inplace=True)
otherstmap.rename(columns={"Count":"Missing"},inplace=True)

otherloc=osvc.groupby("Location").agg(Count=("State_Name","count"))
otherlocmap = worldmap.merge(
    maplocationcount.reset_index(),
    left_on="name",
    right_on="Location",
    how="left"
    )

otherlocmap.drop(columns={"ISO3166-1-Alpha-2","ISO3166-1-Alpha-3", "Location"},inplace=True)
otherlocmap.rename(columns={"Count":"Missing"},inplace=True)
```
```{python}
#|echo: false
miadfs = {
  "usmap":usmap,
  "worldmap":worldmap,
  "maplocationcount":maplocationcount,
  "bysvc":bysvc,
  "srv_cnf":srv_cnf,
  "ww2_stmap":ww2_stmap,
  "kwar_stmap":kwar_stmap,
  "vwar_stmap":vwar_stmap,
  "owar_stmap":owar_stmap,
  "ww2_locmap":ww2_locmap,
  "kwar_locmap":kwar_locmap,
  "vwar_locmap":vwar_locmap,
  "owar_locmap":owar_locmap,
  "afstmap":afstmap,
  "armystmap":armystmap,
  "navystmap":navystmap,
  "mcstmap":mcstmap,
  "otherstmap":otherstmap,
  "aflocmap":aflocmap,
  "armylocmap":armylocmap,
  "navylocmap":navylocmap,
  "mclocmap":mclocmap,
  "otherlocmap":otherlocmap
  }

with open("miadfs.pkl","wb") as f: pickle.dump(miadfs, f)

```



