---
title: "MIA Data Conflict Analysis"
author: "Ray Erickson"
date: today
format:
  html:
    theme: spacelab
    backgroundcolor: "#DCDCE3"
    monobackgroundcolor: "#DEDEDE"
    fontcolor: "black"
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: false
    code-overflow: wrap
    embed-resources: true
    tabsets: true
editor_options:
  markdown:
    wrap: none
jupyter: python3
---
```{python setup, include=FALSEE}
#| echo: False
#Importing the needed libraries
import pandas as pd
import matplotlib.pyplot as plt
import us
import geopandas
import pickle
```

# Conflict Analysis & Conclusion


For this project you will need the `pandas`, `matplotlib.pyplot`, `us`, `geopandas`, and `re` libraries

Also, due to the size of the data, this project is split into three files, so `pickle` is needed in order to export the variables from one doc to the other

```{python}
#|echo: false

with open("miadfs.pkl", "rb") as f:
  miadfs = pickle.load(f)

#bysvc = miadfs["bysvc"]
ww2_stmap = miadfs["ww2_stmap"]
kwar_stmap = miadfs["kwar_stmap"]
vwar_stmap = miadfs["vwar_stmap"]
owar_stmap = miadfs["owar_stmap"]
ww2_locmap = miadfs["ww2_locmap"]
kwar_locmap = miadfs["kwar_locmap"]
vwar_locmap = miadfs["vwar_locmap"]
owar_locmap = miadfs["owar_locmap"]
#srv_cnf = miadfs["srv_cnf"]
```

:::{.panel-tabset}

## Analysis

I am also combining the conflicts beside World War II, the Korean War, and the Vietnam War as well as the other services beside the Army, Air Force, Navy, and Marine Corps.

:::{.panel-tabset}

### World War II

```{python}
#|echo: False
print("World War II Missing by State")

ww2_stmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
```

```{python}
#|echo: False
print("World War II Missing by Location")

ww2_locmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
```


### Korean War

```{python}
#|echo: False
print("Korean War Missing by State")

kwar_stmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
```

```{python}
#|echo: False
print("Korean War Missing by Location")

kwar_locmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
```

### Vietnam War

```{python}
#|echo: False
print("Vietnam War Missing by State")

vwar_stmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
```

```{python}
#|echo: False
print("Vietnam War Missing by Location")

vwar_locmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
```

### Other Conflicts

```{python}
#|echo: False
print("Other Conflicts Missing by State")

owar_stmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)

```

```{python}
#|echo: False
print("Other Conflicts Missing by Location")

owar_locmap.explore(column="Missing", legend=True, cmap="YlOrRd", tiles="OpenStreetMap", tooltip=True)
```


:::

## Conclusions

World War II is overwhelmingly the originating conflict for the majority of MIA soldiers, as well as the highest percentage of loss for all of the services

Overall the US Navy has the most MIA soldiers. 

California overall has the most MIA soldiers, although New York has more MIA from World War II than California does

California has the most MIA Navy and Marines, while New York has the most MIA Army, Air Force, and other services

The Solomon Islands have the highest concentration of MIA missing, including the highest concentration of Marine Corps and Navy missing, as well as the highest concentration of World War II missing.

North Korea has the highest concentration of both Korean War missing, and Army missing.

Papua New Guinea has the highest concentration of Air Force missing.

The highest concentration of missing from other conflicts is in Russia, while the highest concentration of missing from other services is Greenland.

:::